name: Push CI

on: push

jobs:
  textformat:
    name: EditorConfig audit
    runs-on: ubuntu-latest
    env:
      ALWAYS_LINT_ALL_FILES: false
      EC_FIX_ERROR: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: EditorConfig-Action
        uses: zbeekman/EditorConfig-Action@master
        env:
          ALWAYS_LINT_ALL_FILES: false
          EC_FIX_ERROR: false

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: esp-idf build
      uses: sebastianPsm/esp-idf-ci-action@1
